name: Checkout and build icecube-simulation framework
description: Install dependencies, fetch icecube-simulation-framework sourcecode from svn, and build the icecube-simulation framework.
author: Sebastian Fiedlschuster
inputs:
  release:
    description: The release number of the icecube-simulation framework you would like to install. May be a release like "V06-01-01", or "trunk", which will fetch the current svn trunk of the framework.
    default: V06-01-01
  platform:
    description: "The operating system, the script will run on. This is needed to install the dependencies with the appropriate package manager. Supported: ubuntu-18.04, macOS-10.14"
    default: ubuntu-18.04
  svn:
    description: "The url of our svn repository, ending with '/svn': 'http://code..../svn'"
    required: true
  svn_icecube_username:
    description: The svn user to use to fetch the icecube-simulation sourcecode.
    default: icecube
  svn_icecube_password:
    description: The svn password to use to fetch the icecube-simulation sourcecode.
    required: true
runs:
  using: "node12"
  main: "index.js"
  env:
    RELEASE: ${{ inputs.release }}
    PLATFORM: ${{ inputs.platform }}
    SVN: ${{ inputs.svn }}
    SVN_ICECUBE_USERNAME: ${{ inputs.svn_icecube_username }}
    SVN_ICECUBE_PASSWORD: ${{ inputs.svn_icecube_password }}
branding:
  icon: code
  color: blue