name: build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        release: [V06-01-01, trunk]
        platform: [macOS-10.14]

    steps:
    - uses: actions/checkout@v1
    - name: Build icecube-simulation
      run: bash -v -e ./install-on-mac-os.sh
      env:
        RELEASE: ${{ matrix.release }}
        SVN: ${{ secrets.SVN }}
        SVN_ICECUBE_USERNAME: icecube
        SVN_ICECUBE_PASSWORD: ${{ secrets.SVN_ICECUBE_PASSWORD }}
