name: build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform: [macOS-10.14, ubuntu-18.04]

    steps:
    - uses: actions/checkout@v1
    - name: Build icecube-combo
      run: bash -v -e ./install.sh
      env:
        GIT_REPO_URL: ${{ secrets.GIT_REPO_URL }}
        PLATFORM: ${{ matrix.platform }}
