name: build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        release: [V06-01-01, trunk]
        platform: [macOS-10.14, ubuntu-18.04]

    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        release: ${{ matrix.release }}
        platform: ${{ matrix.platform }}
        svn: ${{ secrets.SVN }}
        svn_icecube_username: icecube
        svn_icecube_password: ${{ secrets.SVN_ICECUBE_PASSWORD }}
    #- name: Build icecube-simulation
    #  run: bash -v -e ./install.sh
    #  env:
    #    RELEASE: ${{ matrix.release }}
    #    SVN: ${{ secrets.SVN }}
    #    SVN_ICECUBE_USERNAME: icecube
    #    SVN_ICECUBE_PASSWORD: ${{ secrets.SVN_ICECUBE_PASSWORD }}
    #    PLATFORM: ${{ matrix.platform }}
