name: build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        release: [V00-00-00-RC2, stable, trunk]
        platform: [macOS-10.14, ubuntu-18.04]

    steps:
    - uses: actions/checkout@v1
    - name: Build icecube-combo
      run: bash -v -e ./install.sh
      env:
        RELEASE: ${{ matrix.release }}
        SVN: ${{ secrets.SVN }}
        SVN_ICECUBE_USERNAME: icecube
        SVN_ICECUBE_PASSWORD: ${{ secrets.SVN_ICECUBE_PASSWORD }}
        PLATFORM: ${{ matrix.platform }}
